title: Fred Talks | Des petites solutions pour des petits problèmes
email: frederic.gillouard@gmail.com
description: >
   Fred Talks | Des petites solutions pour des petits problèmes
baseurl: ""
url: ""
github_username:  draoullig

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
plugins:
  - jekyll-feed