title: Fred Talks
email: frederic.gillouard@gmail.com
description: >
  Des petites solutions pour des petits problèmes…
baseurl: ""
url: ""
github_username:  draoullig
gems: [jekyll-paginate]
paginate: 5